loguru_bench/CMakeLists.txt
loguru_example/CMakeLists.txt
test/CMakeLists.txt

When I tried to build the test and the example program of loguru. I had the following error:
CMake Error at CMakeLists.txt:12 (add_compile_options):
Unknown CMake command "add_compile_options"
It seems the CMake command *add_compile_option()* is available in CMake 2.8.12 and later, and I have the version 2.8.7. So, in order to allow the users to build the test program and the examples using an older version of CMake, I added a support of that using the *set()* command.
This solution should work on every versions that have the support of this command, including the latest versions of CMake.

Fixed an issue while building the example and test programs using an older version of CMake

---

loguru.hpp

Cygwin uses its own C library, which does not include the
execinfo.h header. To successfully compile Loguru in Cygwin
backtraces have to be disabled.

Support for Cygwin

---

README.md
loguru.hpp

[Fmtlib](https://github.com/fmtlib/fmt) has nice alternative, pythonlike, formatting. This patch allows fmtlib to be used by defining `LOGURU_USE_FMTLIB`
Tnx for sharing the `loguru` library btw 👍

Support fmtlib formatting

---

loguru.hpp
test/CMakeLists.txt

A macro ``LOGURU_WITH_FILEABS`` is added.
when ``LOGURU_WITH_FILEABS`` is defined, a check of file change will be performed on every call to ``file_log``. If the file is moved, or inode changes, file is reopened using the same ``FileMode`` as is done by ``add_file``.
``file_log`` is made sequential using pthread lock since every call of ``file_log`` may reopen the file and invalidate the file descriptor. Hence calling ``file_log`` from multiple threads is OK.
Such a scheme is useful if you have a daemon program that moves the log file every 24 hours and expects new file to be created.
If one thread calls remove_callback while others are logging into this file, an error will probably occur. But I will let it be since I guess the very problem exists in the original design.

Implement a new feature

---

loguru.hpp

It is a bug (by me).
When a new file descriptor is opened, the old one should be closed. I just found out that I neglected this.

add missing fclose in file_reopen

---

loguru.hpp

Introduced `LOGURU_DEBUG_CHECKS` and `LOGURU_DEBUG_LOGGING` to explicitly and separately control
debug versions of the check- and logging-macros, independent of `NDEBUG`. This can for instance be
used to create a release build with assertions enabled.

Added support for explicitly enabling debug logging or checks

---

loguru.hpp

Hi,
I've just started using this library and noticed a couple of issues during the compilation on Win. Most importantly, "_strerror_s" was used incorrectly and there was a #ifdef WINDOWS check that was never defined.
I also added support for terminal colors on Windows 10 (support checked at runtime and simply disabled for older versions). Unfortunately this required me to define more verbose sequence codes, because the \e variant doesn't work on Windows (See diff).

Improved Windows support

---

loguru.hpp

`typeid()` is incompatible with `-fno-rtti` (which is required when linking against LLVM C++ libraries).
This PR makes it possible to disable code that uses `typeid()` with `-DLOGURU_STACKTRACES=0` so that an object file can use both loguru and LLVM C++ libraries.
This is in preparation for using clang C++ API in  https://github.com/jacobdufault/cquery/

Allow LOGURU_STACKTRACES to be overriden

---

loguru.hpp

Maybe we should use explicit `defined` instead of `!defined` for these POSIX systems.

Fix pthread_{get,set}name build error on OpenIndiana

---

loguru.hpp

There are other libc libraries like musl, which only provide the XSI version. It should also work if glibc is configured to provide the XSI version.

Use XSI version of strerror_r on non glibc environments

---

loguru.hpp

Tested with clang++ 5.0.0 from MSYS2. `_WIN32` is also defined for Visual Studio.

Let Clang and GCC also use WinAPI on Windows, fix #51

---

README.md
loguru.hpp

Borrowed some #ifdefs from https://gist.github.com/brimston3/2be168bb423c83b0f469c0be56e66d31 for auto-detecting if rtti is enabled. 
Copy/pasted the #define config options into the README
so that they are more obvious to new users / people looking
around at logging libraries.  Fixes #61.

auto-detect rtti. copy some config info into the README.md.

---

loguru.hpp

Allow the application to decide the resolution of the scope timers without needing to edit the `loguru.hpp` header.

Expose SCOPE_TIME_PRECISION setting to applications.

---

loguru.hpp

Addresses upstream issue #67.
By default, these macros are undefined and have no effect on the compiled code. However, if an application defines `LOGURU_EXPORT` with an appropriate export declaration, the necessary symbols will be exposed in the shared library's interface.

Add export stubs to support shared libraries.

---

loguru.hpp

This macro should be defined to 0 or 1 to disable/enable, but was tested with `#ifdef` such that it was always enabled.

Fix REDEFINE_ASSERT behavior.

---

loguru.hpp

This patch adds the ability to set a custom name for each log level.
My only concern is that it adds a bit of overhead by introducing more mutex locks, but this is worthwhile for the improved readability in our application. C++17's `shared_mutex` would likely make this a non-issue, since the most frequent accessed are for reading only. But for now, this just locks the existing loguru mutex.

Allow custom level names in log output and arg parsing.

---

loguru.hpp

Thanks for making loguru. I thought about doing a slightly fancier version of this (with an alternate macro), but this simple flag met my needs for now. Barely merits a pull request, but here it is anyway.

added LOGURU_VERBOSE_SCOPE_ENDINGS to disable verbose scope endings

---

loguru.cpp
loguru.hpp

Hi there,
Attached some changes to silence compiler warnings.
47cae1c Deactivates the diagnostic pragmas on Windows as VS doesn't recognise them.
576caad Visual Studio complains about an unofficial strdup which we all know works everywhere, but as it turns out is not part of the official spec. This commit changes the use of strdup per os.
54a6613 On windows `right_align_hext_id` is not used and Visual studio complains about that.
There are other ways to achieve the same, but see this as a proposal.

Some minor changes to silence compiler warnings

---

loguru.cpp

Some versions of screen use this TERM value instead. For example, some versions of Ubuntu and Amazon Linux it seems.
https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1726826

Add "screen.xterm-256color" as a recognized color TERM value

---

loguru.cpp

This commit will get rid of the signed/unsigned mismatch warnings that are generated by MSVC due to lack of explicit casting. 
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?view=vs-2019

Add pragmas to disable msvc warning 4018

---

docs/index.html
loguru.cpp
loguru.hpp

Closes https://github.com/emilk/loguru/issues/117
Helps https://github.com/emilk/loguru/issues/94 and https://github.com/emilk/loguru/issues/103
This is a breaking change for a minority of people, but it will be a compile-time failure with helpful errors messages.

Runtime options

---

loguru.cpp

Unlike Android, FreeBSD has execinfo.h, but doesn't have all the
symbols (missing at least backtrace and backtrace_symbols).
This change treats FreeBSD like Android and RTEMS systems, i.e.
pthreads but no stacktrace support unless forced to do so.

Don't try to enable stacktraces on FreeBSD by default

---

loguru.cpp

Currently, the type of terminal (`$TERM`) is checked in `s_terminal_has_color()` to decide if colors are supported. However, the `stderr` can be redirected to a file or another process which doesn't support colors. To check if `stderr` is being received by a terminal, at least the `isatty()` POSIX function must be called.
More advanced checks like `ttyname()` could be used.

Check isatty() to decide if colors are supported

---

docs/index.html
loguru.cpp
loguru_example/CMakeLists.txt

Clang 10 will complain 2 kinds of errors in *loguru.cpp*:
- disabled expansion of recursive macro [-Wdisabled-macro-expansion]: line 1784
- implicit conversion from 'long long' to 'double' may lose precision [-Wimplicit-int-float-conversion]: line 1443
A simple switch off the warning will work.

Fix typo and make it success when build with Clang 10

---

loguru.cpp

Allows user to opt out of uset thread local storage for thread names. For some reason, I get weird hex names when using ptls for thread names on my system:
`2020-06-16 20:53:22.134 (   2.817s) [         AF61228]`
Without using ptls names everyhing works correctly.

Allow user to disable ptls names

---

docs/index.html
loguru.cpp
loguru.hpp

Inspired by https://github.com/emilk/loguru/pull/150
I regret being lazy and making most options compile-time options. This PR converts `LOGURU_CATCH_SIGABRT` to a runtime options, and adds options to opt-out of catching other signals too.
This is the first C++ code I've written in two years, and I must say... I don't miss it it.

replace LOGURU_CATCH_SIGABRT with struct SignalOptions

---

loguru.cpp

In the relevant use cases, Solaris/illumos has roughly the same API as Linux.

Enabled support for pthreads on Solaris/illumos

---

loguru.cpp
loguru.hpp

This PR proposes to rename the `SignalOptions` member in `Options` from `signals` to `signal_options`.
This avoids issues if the popular Qt library, which defines a macro called `signals` (see https://doc.qt.io/qt-5/signalsandslots.html), is included before loguru.
The `install_signal_handlers` function already calls its argument `const SignalOptions& signal_options`.

Rename signals to signal_options

---

loguru.cpp

This minor change prevents the MSVC warning C4244 `conversion from 'unsigned __int64' to 'const size_t', possible loss of data` from being emitted on 32-bit builds

Use size_t type for get_thread_name length

---

loguru.cpp

`_dupenv_s` isn't available when compiling with MinGW (e.g. #128). This PR retrieves the Windows-specific `USERPROFILE` environment variable with the default `getenv` function.
Tested with MinGW 7.3.0 and MSVC14.22.

Avoid MSVC-specific functions with MinGW

---

loguru.cpp

1. Fix not applying `GCC diagnostic ignored` on clang on Windows
2. Fix underlying code causing the sign comparison warnings

Fix clang on windows warnings

---

loguru.cpp

Add a simple solution to a compilation warning that doesn't require any special changes to be made to already existing enums, types or logic.
```
loguru/loguru.cpp: In function ‘void loguru::print_preamble(char*, size_t, loguru::Verbosity, const char*, unsigned int)’:
loguru/loguru.cpp:1208:50: warning: ‘% 4d’ directive output may be truncated writing between 4 and 11 bytes into a region of size 5 [-Wformat-truncation=]
1208 |    snprintf(level_buff, sizeof(level_buff) - 1, "% 4d", verbosity);
|                                                  ^~~~
loguru/loguru.cpp:1208:49: note: directive argument in the range [1, 2147483647]
1208 |    snprintf(level_buff, sizeof(level_buff) - 1, "% 4d", verbosity);
|                                                 ^~~~~~
In file included from …
```

Fix a compilation warning - directive output may be truncated

---

loguru.cpp
loguru.hpp

These proposed changes are being used in the forked version Loguru used in ECP VTK-m.
Proposed changes are split into two commits:
- Encapsulate functions using anonymous, needed for other libraries using this libraries not to export the loguru namespace to avoid possible conflict when there are two libraries/binaries using different Loguru versions and being statically linked together.
- Add va_list version of the core functions, varadic MACROS are impossible to opaquely wrap, in this commit I propose an alternative.

add va_list versions of log functions and add optional anonymous namespace

---

loguru.cpp
loguru.hpp

Application developers can use the established `LOGURU_USE_` mechanism to toggle the use of LOCALE:
`#define LOGURU_USE_LOCALE 1` (or 0)
.. Or nothing, which will use LOCALE by default.
Application developers may want to avoid calls into the the host's locale system, which can cause problems if the external application is expecting to use a narrow character set but gets a wide character set (and vice-versa).

Make the use of locale optional via `LOGURU_USE_LOCALE`

---

loguru.cpp

My apologies, closed the previous issue (#213) by accidentally deleting my branch !
Changes:
- Fixes #126
Notes:
- This fix was suggested by @lkho and it works perfectly, thanks!
- It might makes sense to allow shared read access but prevent shared write?
This could be accomplished by switch `_SH_DENYNO` to `_SH_DENYWR`.

Reopened: Fix exclusive file-lock on Windows

---

loguru.hpp

simple CHECK_EQ_F(int64, int64) will throw unexpected exception when LOGURU_USE_FMTLIB defined

fix bug: CHECK_EQ_F(int64, int64)
